export const LCEntries = [
{"D": "Afar", "C": "aa"},
{"D": "Abkhazian", "C": "ab"},
{"D": "Avestan", "C": "ae"},
{"D": "Afrikaans", "C": "af"},
{"D": "Akan", "C": "ak"},
{"D": "Amharic", "C": "am"},
{"D": "Aragonese", "C": "an"},
{"D": "Arabic", "C": "ar"},
{"D": "Assamese", "C": "as"},
{"D": "Avaric", "C": "av"},
{"D": "Aymara", "C": "ay"},
{"D": "Azerbaijani", "C": "az"},
{"D": "Bashkir", "C": "ba"},
{"D": "Belarusian", "C": "be"},
{"D": "Bulgarian", "C": "bg"},
{"D": "Bihari languages", "C": "bh"},
{"D": "Bislama", "C": "bi"},
{"D": "Bambara", "C": "bm"},
{"D": "Bengali", "C": "bn"},
{"D": "Tibetan", "C": "bo"},
{"D": "Breton", "C": "br"},
{"D": "Bosnian", "C": "bs"},
{"D": "Catalan; Valencian", "C": "ca"},
{"D": "Chechen", "C": "ce"},
{"D": "Chamorro", "C": "ch"},
{"D": "Corsican", "C": "co"},
{"D": "Cree", "C": "cr"},
{"D": "Czech", "C": "cs"},
{"D": "Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic", "C": "cu"},
{"D": "Chuvash", "C": "cv"},
{"D": "Welsh", "C": "cy"},
{"D": "Danish", "C": "da"},
{"D": "German", "C": "de"},
{"D": "Divehi; Dhivehi; Maldivian", "C": "dv"},
{"D": "Dzongkha", "C": "dz"},
{"D": "Ewe", "C": "ee"},
{"D": "Greek, Modern (1453-)", "C": "el"},
{"D": "English", "C": "en"},
{"D": "Esperanto", "C": "eo"},
{"D": "Spanish; Castilian", "C": "es"},
{"D": "Estonian", "C": "et"},
{"D": "Basque", "C": "eu"},
{"D": "Persian", "C": "fa"},
{"D": "Fulah", "C": "ff"},
{"D": "Finnish", "C": "fi"},
{"D": "Fijian", "C": "fj"},
{"D": "Faroese", "C": "fo"},
{"D": "French", "C": "fr"},
{"D": "Western Frisian", "C": "fy"},
{"D": "Irish", "C": "ga"},
{"D": "Gaelic; Scottish Gaelic", "C": "gd"},
{"D": "Galician", "C": "gl"},
{"D": "Guarani", "C": "gn"},
{"D": "Gujarati", "C": "gu"},
{"D": "Manx", "C": "gv"},
{"D": "Hausa", "C": "ha"},
{"D": "Hebrew", "C": "he"},
{"D": "Hindi", "C": "hi"},
{"D": "Hiri Motu", "C": "ho"},
{"D": "Croatian", "C": "hr"},
{"D": "Haitian; Haitian Creole", "C": "ht"},
{"D": "Hungarian", "C": "hu"},
{"D": "Armenian", "C": "hy"},
{"D": "Herero", "C": "hz"},
{"D": "Interlingua (International Auxiliary Language Association)", "C": "ia"},
{"D": "Indonesian", "C": "id"},
{"D": "Interlingue; Occidental", "C": "ie"},
{"D": "Igbo", "C": "ig"},
{"D": "Sichuan Yi; Nuosu", "C": "ii"},
{"D": "Inupiaq", "C": "ik"},
{"D": "Ido", "C": "io"},
{"D": "Icelandic", "C": "is"},
{"D": "Italian", "C": "it"},
{"D": "Inuktitut", "C": "iu"},
{"D": "Japanese", "C": "ja"},
{"D": "Javanese", "C": "jv"},
{"D": "Georgian", "C": "ka"},
{"D": "Kongo", "C": "kg"},
{"D": "Kikuyu; Gikuyu", "C": "ki"},
{"D": "Kuanyama; Kwanyama", "C": "kj"},
{"D": "Kazakh", "C": "kk"},
{"D": "Kalaallisut; Greenlandic", "C": "kl"},
{"D": "Central Khmer", "C": "km"},
{"D": "Kannada", "C": "kn"},
{"D": "Korean", "C": "ko"},
{"D": "Kanuri", "C": "kr"},
{"D": "Kashmiri", "C": "ks"},
{"D": "Kurdish", "C": "ku"},
{"D": "Komi", "C": "kv"},
{"D": "Cornish", "C": "kw"},
{"D": "Kirghiz; Kyrgyz", "C": "ky"},
{"D": "Latin", "C": "la"},
{"D": "Luxembourgish; Letzeburgesch", "C": "lb"},
{"D": "Ganda", "C": "lg"},
{"D": "Limburgan; Limburger; Limburgish", "C": "li"},
{"D": "Lingala", "C": "ln"},
{"D": "Lao", "C": "lo"},
{"D": "Lithuanian", "C": "lt"},
{"D": "Luba-Katanga", "C": "lu"},
{"D": "Latvian", "C": "lv"},
{"D": "Malagasy", "C": "mg"},
{"D": "Marshallese", "C": "mh"},
{"D": "Maori", "C": "mi"},
{"D": "Macedonian", "C": "mk"},
{"D": "Malayalam", "C": "ml"},
{"D": "Mongolian", "C": "mn"},
{"D": "Marathi", "C": "mr"},
{"D": "Malay", "C": "ms"},
{"D": "Maltese", "C": "mt"},
{"D": "Burmese", "C": "my"},
{"D": "Nauru", "C": "na"},
{"D": "Bokm\u00e5l, Norwegian; Norwegian Bokm\u00e5l", "C": "nb"},
{"D": "Ndebele, North; North Ndebele", "C": "nd"},
{"D": "Nepali", "C": "ne"},
{"D": "Ndonga", "C": "ng"},
{"D": "Dutch; Flemish", "C": "nl"},
{"D": "Norwegian Nynorsk; Nynorsk, Norwegian", "C": "nn"},
{"D": "Norwegian", "C": "no"},
{"D": "Ndebele, South; South Ndebele", "C": "nr"},
{"D": "Navajo; Navaho", "C": "nv"},
{"D": "Chichewa; Chewa; Nyanja", "C": "ny"},
{"D": "Occitan (post 1500)", "C": "oc"},
{"D": "Ojibwa", "C": "oj"},
{"D": "Oromo", "C": "om"},
{"D": "Oriya", "C": "or"},
{"D": "Ossetian; Ossetic", "C": "os"},
{"D": "Panjabi; Punjabi", "C": "pa"},
{"D": "Pali", "C": "pi"},
{"D": "Polish", "C": "pl"},
{"D": "Pushto; Pashto", "C": "ps"},
{"D": "Portuguese", "C": "pt"},
{"D": "Quechua", "C": "qu"},
{"D": "Romansh", "C": "rm"},
{"D": "Rundi", "C": "rn"},
{"D": "Romanian; Moldavian; Moldovan", "C": "ro"},
{"D": "Russian", "C": "ru"},
{"D": "Kinyarwanda", "C": "rw"},
{"D": "Sanskrit", "C": "sa"},
{"D": "Sardinian", "C": "sc"},
{"D": "Sindhi", "C": "sd"},
{"D": "Northern Sami", "C": "se"},
{"D": "Sango", "C": "sg"},
{"D": "Sinhala; Sinhalese", "C": "si"},
{"D": "Slovak", "C": "sk"},
{"D": "Slovenian", "C": "sl"},
{"D": "Samoan", "C": "sm"},
{"D": "Shona", "C": "sn"},
{"D": "Somali", "C": "so"},
{"D": "Albanian", "C": "sq"},
{"D": "Serbian", "C": "sr"},
{"D": "Swati", "C": "ss"},
{"D": "Sotho, Southern", "C": "st"},
{"D": "Sundanese", "C": "su"},
{"D": "Swedish", "C": "sv"},
{"D": "Swahili", "C": "sw"},
{"D": "Tamil", "C": "ta"},
{"D": "Telugu", "C": "te"},
{"D": "Tajik", "C": "tg"},
{"D": "Thai", "C": "th"},
{"D": "Tigrinya", "C": "ti"},
{"D": "Turkmen", "C": "tk"},
{"D": "Tagalog", "C": "tl"},
{"D": "Tswana", "C": "tn"},
{"D": "Tonga (Tonga Islands)", "C": "to"},
{"D": "Turkish", "C": "tr"},
{"D": "Tsonga", "C": "ts"},
{"D": "Tatar", "C": "tt"},
{"D": "Twi", "C": "tw"},
{"D": "Tahitian", "C": "ty"},
{"D": "Uighur; Uyghur", "C": "ug"},
{"D": "Ukrainian", "C": "uk"},
{"D": "Urdu", "C": "ur"},
{"D": "Uzbek", "C": "uz"},
{"D": "Venda", "C": "ve"},
{"D": "Vietnamese", "C": "vi"},
{"D": "Volap\u00fck", "C": "vo"},
{"D": "Walloon", "C": "wa"},
{"D": "Wolof", "C": "wo"},
{"D": "Xhosa", "C": "xh"},
{"D": "Yiddish", "C": "yi"},
{"D": "Yoruba", "C": "yo"},
{"D": "Zhuang; Chuang", "C": "za"},
{"D": "Chinese", "C": "zh"},
{"D": "Zulu", "C": "zu"}
]